### ISSUE TITLE
Error on launch on mac

### ISSUE THREAD

**Issue by ishandutta2007** [donatj/imgdedup#2]
Steps to reproduce:
1. Downloaded darwin_386.zip
2. Extracted everything.
3. Copied `imgdedup` to `/usr/local/bin/.`
4. On terminal ran  `imgdedup`

> fatal error: still in list
> 
> runtime stack:
> runtime.throw(0x23bbab)
> 	/Users/jdonat/go/src/runtime/panic.go:491 +0x83 fp=0xbffff7f0 sp=0xbffff7d8
> MHeap_AllocSpanLocked(0x254440, 0x1, 0x0)
> 	/Users/jdonat/go/src/runtime/mheap.c:349 +0x282 fp=0xbffff810 sp=0xbffff7f0
> mheap_alloc(0x254440, 0x1, 0xb, 0x0, 0x0)
> 	/Users/jdonat/go/src/runtime/mheap.c:190 +0xec fp=0xbffff824 sp=0xbffff810
> runtime.MHeap_Alloc(0x254440, 0x1, 0xb, 0x100, 0xf2d2)
> 	/Users/jdonat/go/src/runtime/mheap.c:240 +0x54 fp=0xbffff844 sp=0xbffff824
> MCentral_Grow(0x258934, 0x0)
> 	/Users/jdonat/go/src/runtime/mcentral.c:197 +0x65 fp=0xbffff87c sp=0xbffff844
> runtime.MCentral_CacheSpan(0x258934, 0x0)
> 	/Users/jdonat/go/src/runtime/mcentral.c:85 +0x11c fp=0xbffff8a0 sp=0xbffff87c
> runtime.MCache_Refill(0x30448000, 0xb, 0x0)
> 	/Users/jdonat/go/src/runtime/mcache.c:90 +0x77 fp=0xbffff8b4 sp=0xbffff8a0
> runtime.mcacheRefill_m()
> 	/Users/jdonat/go/src/runtime/malloc.c:368 +0x42 fp=0xbffff8c4 sp=0xbffff8b4
> runtime.onM(0x1c1f6c)
> 	/Users/jdonat/go/src/runtime/asm_386.s:282 +0x70 fp=0xbffff8c8 sp=0xbffff8c4
> runtime.mallocgc(0xa0, 0x172200, 0x0, 0x2485a0)
> 	/Users/jdonat/go/src/runtime/malloc.go:178 +0x688 fp=0xbffff920 sp=0xbffff8c8
> runtime.newobject(0x172200, 0x100000)
> 	/Users/jdonat/go/src/runtime/malloc.go:353 +0x42 fp=0xbffff934 sp=0xbffff920
> runtime.newG(0x30448000)
> 	/Users/jdonat/go/src/runtime/proc.go:233 +0x22 fp=0xbffff940 sp=0xbffff934
> allocg(0x2484a0)
> 	/Users/jdonat/go/src/runtime/proc.c:893 +0x1b fp=0xbffff948 sp=0xbffff940
> runtime.malg(0x8000, 0x2485a0)
> 	/Users/jdonat/go/src/runtime/proc.c:2074 +0x1b fp=0xbffff960 sp=0xbffff948
> runtime.mpreinit(0x2487c0)
> 	/Users/jdonat/go/src/runtime/os_darwin.c:137 +0x23 fp=0xbffff96c sp=0xbffff960
> mcommoninit(0x2487c0)
> 	/Users/jdonat/go/src/runtime/proc.c:201 +0xb2 fp=0xbffff988 sp=0xbffff96c
> runtime.schedinit()
> 	/Users/jdonat/go/src/runtime/proc.c:138 +0x46 fp=0xbffff9a0 sp=0xbffff988
> runtime.rt0_go(0xbffffa34, 0xbffff9f8, 0x2bd427, 0x1000, 0x0, 0x1, 0xbffffa34, 0xbffffa3c, 0xbffffaac, 0xbffffa1c, ...)
> 	/Users/jdonat/go/src/runtime/asm_386.s:100 +0xed fp=0xbffff9a4 sp=0xbffff9a0](url)

**Comment by donatj** [comment]
You probably want to try `darwin_amd64.zip` unless you are on a *very old* Mac. 

I'll tag a new release soon. the one that's up there is 4ish years old. I just want to get some work I did cleaning up the caching ready first.

**Comment by ishandutta2007** [comment]
Done Same error.

**Comment by ishandutta2007** [comment]
Here are my OS details:

`$system_profiler SPSoftwareDataType`

> Software:
> 
>     System Software Overview:
> 
>       System Version: macOS 10.13.6 (17G8030)
>       Kernel Version: Darwin 17.7.0
>       Boot Volume: Macintosh HD
>       Boot Mode: Normal
>       User Name: Ishan Dutta (ishandutta2007)
>       Secure Virtual Memory: Enabled
>       System Integrity Protection: Enabled
>       Time since boot: 20 minutes
> 
>

**Comment by ishandutta2007** [comment]
I don't have much understanding on how to build go from code. I tried the compile step below, it only to clone the code base under the go path I guess, nothing gets installed . Can't go packages be installed by something like `pip` or `npm`?

**Comment by donatj** [comment]
>  Can't go packages be installed by something like pip or npm?

If you installed go, it has a rough approximation with `go get github.com/donatj/imgdedup` but that would take a small amount of setup on your part.

I'll have new binaries shortly.

**Comment by ishandutta2007** [comment]
> I'll have new binaries shortly.
go get just clones the repo under this path: `$HOME/go/src/github.com/donatj/imgdedup/`
What's next ? Can you update install from source docs

**Comment by donatj** [comment]
`go get` also builds a binary. https://golang.org/cmd/go/#hdr-Download_and_install_packages_and_dependencies

The binary would be built into $HOME/go/bin

**Comment by donatj** [comment]
I have a new release compiled with a much more modern version of Go here:

https://github.com/donatj/imgdedup/releases/tag/v0.2.0

Your results should be much better using the binary here.
