### ISSUE TITLE
How to use tolerance ?

### ISSUE THREAD

**Issue by ishandutta2007** [donatj/imgdedup#3]
I have multiple visually identical files(might have different size and aspect ratio)
On running this is what I see.
When I run for full directory which has few pairs and triplets of duplicated images

```
ishandutta2007@MacBook-Pro:~/Documents/Projects$  imgdedup ~/Dropbox/vushka/
 27 / 27 [===============================================================================================================================] 100.00% 3s
```

When I run with two particular images as argument (which are visually identical)

```
ishandutta2007@MacBook-Pro:~/Documents/Projects$  imgdedup ~/Dropbox/vushka/2019-07-30_13-43-59_UTC_cheeku_loves_cheeki.jpg ~/Dropbox/vushka/2019-07-30_13-50-08_UTC_virushka_always.jpg 
 2 / 2 [=================================================================================================================================] 100.00% 0s
```

Nothing got deleted or flagged
I guess I need to tweak tolerance to get results.

**Comment by donatj** [comment]
If there were duplicates, they'd get presented like 

![image](https://user-images.githubusercontent.com/133747/63529093-bf644180-c4c9-11e9-9319-45e43139dc8e.png)

**Comment by donatj** [comment]
If you increase the tolerance for what gets marked as a duplicate, you can get more results.

```
$ imgdedup -tolerance 200  ~/Dropbox/vushka/
```

As noted in the argument help, 100 is the default value, the bigger you make the number, the more likely things are to be noted as a duplicate.

**Comment by ishandutta2007** [comment]
So do you compare diff between all pair in a directory? I just ran on a directory with 500 images, but it ran pretty quickly, if it's 500*500 comparisons then its pretty impressive.

**Comment by ishandutta2007** [comment]
Actually I need an API which I want to call from a python. which given me the `Diff` for a given pair. I can call your lib using bash from python and then parse the results, but that wont be a very fancy way to do things, options I am exploring is porting this code as a python lib or using it as it is but expose as a service to return me the `Diff` . What do you say, how should I go about it ?

**Comment by donatj** [comment]
> So do you compare diff between all pair in a directory?  

Yup, I compare everything to everything else. The first scan of an image will be slower, but I build essentially a map of the image and cache that. Once the maps are built I can compare those much quicker so subsequent runs are much quicker.

> I need an API which I want to call from a python

I could pretty easily add a flag that returns the results as JSON if that works for you? Probably be way easier to parse.

**Comment by donatj** [comment]
If you're OK giving me a couple days, this thing is **really old** and needs some refactoring. 

I genuinely wrote it when I was *first* leaning Go and it's not very idiomatic.

**Comment by ishandutta2007** [comment]
> I could pretty easily add a flag that returns the results as JSON if that works for you? Probably be way easier to parse.

great, will wait for this .

**Comment by donatj** [comment]
JSON output was added in the lastest release

https://github.com/donatj/imgdedup/releases/tag/v0.3.0
