### ISSUE TITLE
Correct way to dedup at once

### ISSUE THREAD

**Issue by ishandutta2007** [donatj/imgdedup#4]
How do I get access to the right most file name when ran on full directory?
is this the correct way ? 
`imgdedup -diff="rm -rf $right" -tolerance=100 ~/Dropbox/vushka`

I guess you mentioned `$left` or `$right` for two file case, how should I do when ran on directory?

**Comment by ishandutta2007** [comment]
My bad seems "Command to pass dupe images" can only be name of a difftool.
Would appreciate if you make it a generic command, requires a minor change. I can send you a PR if  you want .

**Comment by donatj** [comment]
My flag text is pretty bad on that I'm afraid. You don't actually get to define a `$left` and `$right`, it simply passes the filenames as the next two arguments.

**Comment by ishandutta2007** [comment]
I was thinking of creating another option alongside `diff` something like `action` to indicate generic command to be pass as post matching action. But owing to Json thing that you mentioned [here](https://github.com/donatj/imgdedup/issues/3#issuecomment-524355006)
I am closing this ticket as of now
